### PR TITLE
Fix auto-scroll by moving to ngx-auto-scroll

### LINKED ISSUE #121: Look into using 'ngx-auto-scroll' for auto scrolling
'ngx-auto-scroll' might make auto scrolling easier.  I tried it and it works really well, we would just need to fix how we're doing images as images still break it (causes 'reflow')

### PR DESCRIPTION
**Pull request by jonnhy12333**
Okay overall I'm pretty excited about this change.  We now have NO auto scroll logic in our code.  The ngx-auto-scroll package worked really well _except_ for content that causes content to shift (images and emojis).  That is the reason that this pull request is so big is that I had to fix those 2 issues to have auto-scroll work properly.  Here is how I fixed these things and some random things:

**Images (Firebase and regular images)**
In order to prevent _reflow_ when loading an image (had to look up content shifting when loading and the term for that is _reflow_), I had to actually set the height/width on the image before it is loaded.  To do this, I created some pipes that are asynchronous that actually download the image and get the height/width from that downloaded image.  It does some more calculations to make sure the max height is not greater than 500 and the max width is not greater than 300.  Images no longer resize with the screen width.  This is something that might be possible in the future, but too much to handle here.  I chose a max width of 300px so that it would look fine on mobile.

**Emojis**
Emojis can actually cause reflow if it is the first time the emoji is loaded.  To solve this problem I could have gone with the image solution above.  I chose not to and decided to process the emoji when uploading to write the large and small dimensions to the database.  This makes displaying the emoji really easy as we can just bind the height/width to those properties.

**Message Processing**
Instead of using the `processMessage` method to turn the message into html, I've extracted each piece of logic into their own pipe.  In the future, if you want to add some new processing, basically just add a new pipe and add it to the message processing.

** Manage Emojis Screen **
- These new dimension properties are visible in the Manage Emojis screen.
- Fixed issue where we weren't showing the large emoji in the emoji details dropdown panel

**Scroll Down Button**
The ngx-auto-scroll gives us an 'isLocked' property that we can use to show a 'Scroll Down' button when the user has begun scrolling away from the auto scroll region:
image

**Performance**
I've tested this by deploying to the strong-guys app to make sure that this didn't add any additional load time.  The scripting time went from around 1.2s --> 1.4s (this was a pretty rough test too, the numbers vary a bunch, sometimes it was even better).  So I don't think this had a huge negative impact on performance.  I did change the number of results we load initially to 100 though to further increase initial load time (especially since we have 'Get More Messages').  We don't seem to need 200 messages on initial load (it's very rare that I've loaded the chat being more than 100 messages behind, and if I did, I could still catch up).

Misc
- Max size of small emojis changed from 32x32 to 24x24 to match what emoji-mart shows
- Moved all emoji related logic to CustomEmojiService
- Changed message animations to be slide in/out from the right/left instead of scaling
- Added the ability to have a native emoji or custom emoji in a tag (will always be small version)
- Added ability to add links to mood

Fixes #121

### CODE REVIEW

**Comment by jonnhy12333** [comment]
Hey idiot instead of saving 4 properties in the db couldn't you just save 1 (the aspect ratio)?

**Comment by greggiannone** [comment]
I think we need to change the message animation every week or so just to keep users on their toes

File: src/app/components/chat-room/chat-room.component.ts [hunk 1]
```diff
@@ -126,51 +104,16 @@ export class ChatRoomComponent implements OnInit, OnDestroy {
...
-    }
-    this.calculateAtBottom();
-  }
-
-  calculateAtBottom() {
-    const bottomPercentage =
-      (this.feedScroll.nativeElement.scrollTop + this.feedScroll.nativeElement.offsetHeight) /
-      this.feedScroll.nativeElement.scrollHeight;
-
-    this.atBottom = bottomPercentage >= 0.99;
```
Comment (greggiannone) [inline src/app/components/chat-room/chat-room.component.ts]: Ughhhhh this makes my day lmao. I hated all this code

File: src/app/components/message/message.component.html [hunk 2]
```diff
@@ -38,7 +38,7 @@
             <span>Delete</span>
           </button>
         </mat-menu>
-        <mat-card-content [innerHTML]="parseMessage(message.message | decrypt | emojify)">
+        <mat-card-content [innerHTML]="message.message | decrypt | emojify | firebaseImage | async | customEmojify | urlToImage | async | codeBlock | urlToLink">
```
Comment (greggiannone) [inline src/app/components/message/message.component.html]: lmao

File: src/app/services/image-size.service.ts [hunk 3]
```diff
@@ -0,0 +1,40 @@
+import { Injectable } from '@angular/core';
+import { Observable, fromEvent } from 'rxjs';
+import { take, map } from 'rxjs/operators';
+
+export interface ISize { width: number; height: number; }
```
Comment (greggiannone) [inline src/app/services/image-size.service.ts]: Ew an `I` prefix, is this the past?

File: src/app/services/image-size.service.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+        }
+      }
+      return {
+        width,
+        height,
+      };
+    }
+    const image = new Image();
+    const onload$ = fromEvent(image, 'load').pipe(take(1), map(mapLoadedImage));
+    image.src = url;
```
Comment (greggiannone) [inline src/app/services/image-size.service.ts]: Can you just do this on the line above `fromEvent` so that you don't need to store `onload$`?

File: src/app/services/custom-emoji.service.ts [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+      return e.map(m => {
+        return { $key: m.key, ...m.payload.val() };
+      });
+    }), take(1)).subscribe(emojis2 => {
+      for (const emoji of emojis2) {
+        console.log('upgrading emoji: ', emoji.shortNames[0], emoji.imageUrl);
+        this.imageSize.getImageSize$(emoji.imageUrl).toPromise().then(nativeSize => {
+          const smallSize = this.calculateEmojiSize(nativeSize, this.EMOJI_SMALL_MAX_SIZE);
+          const largeSize = this.calculateEmojiSize(nativeSize, this.EMOJI_LARGE_MAX_SIZE);
+          console.log('upgrading dance2', smallSize, largeSize, nativeSize);
```
Comment (greggiannone) [inline src/app/services/custom-emoji.service.ts]: 😨

File: src/app/services/custom-emoji.service.ts [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+    });
+  }
+
+  /** Temporary to upgrade emojis in db */
+  upgradeEmojis(): void {
+    this.db.list<CustomEmoji>('custom_emoticons').snapshotChanges().pipe(map(e => {
+      return e.map(m => {
+        return { $key: m.key, ...m.payload.val() };
+      });
+    }), take(1)).subscribe(emojis2 => {
```
Comment (greggiannone) [inline src/app/services/custom-emoji.service.ts]: Why is this called `emojis2` and not `emojis`?

File: src/app/services/custom-emoji.service.ts [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+      for (const emoji of emojis2) {
+        console.log('upgrading emoji: ', emoji.shortNames[0], emoji.imageUrl);
```
Comment (greggiannone) [inline src/app/services/custom-emoji.service.ts]: 😨

File: src/app/components/message/message.component.html (hunk 2 above)
Comment (jonnhy12333) [reply src/app/components/message/message.component.html]: need a shortcut for these pipes!

**Comment by jonnhy12333** [comment]
> I think we need to change the message animation every week or so just to keep users on their toes

GOTTA

File: src/app/services/image-size.service.ts (hunk 4 above)
Comment (jonnhy12333) [reply src/app/services/image-size.service.ts]: yep, moved code around a bit here to make it more readable

File: src/app/services/custom-emoji.service.ts (hunk 6 above)
Comment (jonnhy12333) [reply src/app/services/custom-emoji.service.ts]: fixed

File: src/app/services/custom-emoji.service.ts (hunk 5 above)
Comment (jonnhy12333) [reply src/app/services/custom-emoji.service.ts]: removed

File: src/app/services/custom-emoji.service.ts (hunk 7 above)
Comment (jonnhy12333) [reply src/app/services/custom-emoji.service.ts]: removed

**Comment by jonnhy12333** [comment]
> Hey idiot instead of saving 4 properties in the db couldn't you just save 1 (the aspect ratio)?

yep, now saving native height /width in the db.  Client can do whatever it wants with em

File: src/app/services/image-size.service.ts (hunk 3 above)
Comment (jonnhy12333) [reply src/app/services/image-size.service.ts]: Changed
